### ISSUE TITLE
Conda env yamls are missing

### ISSUE THREAD

**Issue by mstaczek** [wangwenqian21/CS433-PTQ#1]
Hi, we are looking for a simple to install implementation of AdaRound algorithm and found this repository to be particularly interesting.

Could you **please provide .yaml files for conda** to let us recreate the environments that were mentioned in the usage instructions?

**Comment by wangwenqian21** [comment]
It's now updated in codes/baseline.yaml. Or see the updated codes/readme.md for convenience.

**Comment by mstaczek** [comment]
Thanks, AdaRound scripts seem to work after creating the environment from this yaml.
